import json
import re
import uuid
from datetime import datetime
from typing import Optional, Type
from urllib.parse import quote
import google.generativeai as genai
from config import settings
from utils.logger import get_logger
from schemas.report import FIRDraft, ACCIDENT_TYPE_LABELS

logger = get_logger(__name__)


# ── FIR Generation Prompt ────────────────────────────────────

FIR_GENERATION_PROMPT = """
You are a legal assistant helping road accident victims in India file a
First Information Report (FIR). Based on the accident information provided,
generate a structured FIR draft.

LANGUAGE: Generate the FIR in {lang_name}.

ACCIDENT INFORMATION:
Chat history (user's own description of the accident):
{chat_context}

Additional structured details provided:
- Vehicle numbers: {vehicle_numbers}
- Number of witnesses: {witnesses}
- Number of injured: {injuries_count}
- Accident time: {accident_time}
- Accident type: {accident_type}
- Reporting person: {reporting_person}
- Contact: {contact}
- Location (lat, lng): {coordinates}
- Nearest police station: {nearest_police_station}

INSTRUCTIONS:
1. Extract ALL relevant accident details from the chat history above
2. Combine with the structured details provided
3. Write a clear, formal FIR description in {lang_name}
4. Use formal legal language appropriate for Indian police reports
5. If a detail is not available, write null for that field
6. For incident_date: use today if not mentioned ({today})
7. For incident_time: use the provided accident_time or extract from chat
8. For description: write 2-4 formal sentences describing what happened
9. For coordinates format: "LAT°N, LNG°E"

Respond ONLY with a valid JSON object. No markdown. No preamble. No notes.
Exactly this structure:

{{
  "incident_date": "YYYY-MM-DD or null",
  "incident_time": "HH:MM AM/PM or null",
  "location": "full address string or null",
  "coordinates": "lat°N, lng°E or null",
  "accident_type": "formal type description or null",
  "description": "2-4 sentence formal accident description or null",
  "vehicles_involved": ["vehicle number 1", "vehicle number 2"],
  "injuries": "description of injuries or null",
  "injuries_count": number or null,
  "witnesses": "witness description or null",
  "reporting_person": "name or Anonymous",
  "contact": "phone or Available via RoadSoS emergency response",
  "nearest_police_station": "name and phone or null",
  "notes": "any additional relevant details from chat or null"
}}
"""


# ── Plain-text FIR formatter ─────────────────────────────────

def format_fir_as_plain_text(fir: FIRDraft, lang: str = "en") -> str:
    """
    Convert a structured FIRDraft into a readable plain-text document
    suitable for downloading, printing, or sharing via WhatsApp.

    English format:
    ═══════════════════════════════════
    FIRST INFORMATION REPORT (DRAFT)
    Generated by RoadSoS Emergency App
    ═══════════════════════════════════
    Date of Incident : 2026-06-15
    Time of Incident : 09:15 AM
    Location         : NH44, Panipat, Haryana
    Coordinates      : 29.39°N, 76.96°E
    Type of Accident : Two-Wheeler Collision
    ---
    DESCRIPTION:
    [description text]
    ---
    Vehicles Involved : HR26AB1234, DL3CAB9876
    Persons Injured   : 1 person with possible chest injury
    Witnesses         : Approximately 2 bystanders
    ---
    Reported By  : Anonymous
    Contact      : Available via RoadSoS
    Police Station: Panipat City Police Station, +91-180-2637400
    ---
    NOTE: This is an AI-generated draft. Please verify all details
    with the investigating officer before submission.
    ═══════════════════════════════════
    """
    separator = "=" * 45

    if lang == "hi":
        lines = [
            separator,
            "प्रथम सूचना रिपोर्ट (FIR) - ड्राफ्ट",
            "RoadSoS इमरजेंसी ऐप द्वारा जनरेट",
            separator,
        ]
        field_map = [
            ("घटना की तारीख", fir.incident_date),
            ("घटना का समय", fir.incident_time),
            ("स्थान", fir.location),
            ("निर्देशांक", fir.coordinates),
            ("दुर्घटना का प्रकार", fir.accident_type),
        ]
    else:
        lines = [
            separator,
            "FIRST INFORMATION REPORT (DRAFT)",
            "Generated by RoadSoS Emergency App",
            separator,
        ]
        field_map = [
            ("Date of Incident", fir.incident_date),
            ("Time of Incident", fir.incident_time),
            ("Location", fir.location),
            ("Coordinates", fir.coordinates),
            ("Type of Accident", fir.accident_type),
        ]

    for label, value in field_map:
        if value:
            lines.append(f"{label:<20}: {value}")

    lines.append("-" * 45)

    if lang == "hi":
        lines.append("विवरण:")
    else:
        lines.append("DESCRIPTION:")

    if fir.description:
        lines.append(fir.description)
    else:
        lines.append("Details being collected.")

    lines.append("-" * 45)

    if lang == "hi":
        vehicle_label = "शामिल वाहन"
        injury_label = "घायल व्यक्ति"
        witness_label = "गवाह"
        reporter_label = "रिपोर्टकर्ता"
        contact_label = "संपर्क"
        police_label = "पुलिस स्टेशन"
    else:
        vehicle_label = "Vehicles Involved"
        injury_label = "Persons Injured"
        witness_label = "Witnesses"
        reporter_label = "Reported By"
        contact_label = "Contact"
        police_label = "Police Station"

    if fir.vehicles_involved:
        lines.append(
            f"{vehicle_label:<20}: "
            f"{', '.join(fir.vehicles_involved)}"
        )
    if fir.injuries:
        lines.append(f"{injury_label:<20}: {fir.injuries}")
    if fir.witnesses:
        lines.append(f"{witness_label:<20}: {fir.witnesses}")

    lines.append("-" * 45)

    if fir.reporting_person:
        lines.append(f"{reporter_label:<20}: {fir.reporting_person}")
    if fir.contact:
        lines.append(f"{contact_label:<20}: {fir.contact}")
    if fir.nearest_police_station:
        lines.append(f"{police_label:<20}: {fir.nearest_police_station}")

    if fir.notes:
        lines.append("-" * 45)
        lines.append(f"Notes: {fir.notes}")

    lines.append("-" * 45)

    if lang == "hi":
        lines.append(
            "नोट: यह AI-जनरेटेड ड्राफ्ट है। सबमिट करने से पहले"
            " जांच अधिकारी से सभी विवरण सत्यापित करें।"
        )
    else:
        lines.append(
            "NOTE: This is an AI-generated draft. Please verify all"
            " details with the investigating officer before submission."
        )

    lines.append(separator)
    return "\n".join(lines)


def build_fir_whatsapp_url(
    download_text: str,
    report_id: str
) -> str:
    """
    Build a WhatsApp share URL for the FIR plain text.

    WhatsApp has a 4096 character limit for pre-filled messages.
    If the FIR text is too long, truncate with a note.

    Prepend a header line:
      "📋 FIR Draft (Report ID: {report_id})\n\n"
    Then the full FIR text.
    """
    header = f"📋 FIR Draft (Report ID: {report_id})\n\n"
    full_message = header + download_text

    # WhatsApp text limit: 4096 chars
    if len(full_message) > 4000:
        full_message = full_message[:3950] + \
                       "\n\n[... FIR truncated. Full report available " \
                       "in the RoadSoS app ...]"

    encoded = quote(full_message)
    return f"https://wa.me/?text={encoded}"


# ── Main service class ────────────────────────────────────────

class ReportService:

    def __init__(self):
        if not settings.GEMINI_API_KEY:
            raise ValueError("GEMINI_API_KEY not configured")
        genai.configure(api_key=settings.GEMINI_API_KEY)
        self.model = genai.GenerativeModel(
            model_name=settings.GEMINI_MODEL
        )
        self.logger = get_logger(__name__)

    def _extract_chat_context(
        self,
        messages: list,
        max_chars: int = 3000
    ) -> str:
        """
        Extract relevant text from chat session messages.

        Rules:
        1. Include ONLY user messages (role="user") — assistant replies
           are the AI's own words, not the victim's account
        2. Strip any INTENT: lines from messages
        3. Label each message with turn number: "User said: ..."
        4. Truncate to max_chars from the END (most recent context)
           — most recent messages have the most relevant details
        5. If no messages: return "No chat history available."
        """
        if not messages:
            return "No chat history available."

        user_messages = []
        for i, msg in enumerate(messages):
            if msg.get("role") == "user":
                content = msg.get("content", "").strip()
                if content:
                    user_messages.append(f"Turn {len(user_messages)+1}: {content}")

        if not user_messages:
            return "No user messages in chat history."

        combined = "\n".join(user_messages)

        # Truncate from the end if too long
        if len(combined) > max_chars:
            combined = "...(earlier messages omitted)...\n" + \
                       combined[-max_chars:]

        return combined

    def generate_fir(
        self,
        chat_context: str,
        additional_info,      # AdditionalReportInfo schema object
        lat: Optional[float],
        lng: Optional[float],
        nearest_police: Optional[str],
        lang: str = "en"
    ) -> FIRDraft:
        """
        Call Gemini to generate a structured FIR draft.
        This is SYNCHRONOUS — call via asyncio.to_thread() from endpoints.

        Returns a FIRDraft object.

        Error handling:
        - If Gemini returns invalid JSON: use fallback FIR builder
        - If Gemini API fails: use fallback FIR builder
        - Never raise — always return a FIRDraft (even if minimal)
        """
        lang_name = "Hindi" if lang == "hi" else "English"

        # Format vehicle numbers
        vehicle_str = (
            ", ".join(additional_info.vehicle_numbers)
            if additional_info.vehicle_numbers
            else "Not provided"
        )

        # Format coordinates
        coord_str = "Not available"
        if lat and lng:
            coord_str = f"{lat:.4f}°N, {lng:.4f}°E"

        # Format accident type
        accident_type_str = "Not specified"
        if additional_info.accident_type:
            type_labels = ACCIDENT_TYPE_LABELS.get(lang, ACCIDENT_TYPE_LABELS["en"])
            accident_type_str = type_labels.get(
                additional_info.accident_type,
                additional_info.accident_type
            )

        prompt = FIR_GENERATION_PROMPT.format(
            lang_name=lang_name,
            chat_context=chat_context,
            vehicle_numbers=vehicle_str,
            witnesses=additional_info.witnesses or "Not specified",
            injuries_count=additional_info.injuries_count or "Not specified",
            accident_time=additional_info.accident_time or "Not specified",
            accident_type=accident_type_str,
            reporting_person=additional_info.reporting_person_name or "Anonymous",
            contact=additional_info.reporting_person_phone or
                    "Available via RoadSoS emergency response",
            coordinates=coord_str,
            nearest_police_station=nearest_police or "Nearest police station",
            today=datetime.utcnow().strftime("%Y-%m-%d")
        )

        try:
            self.logger.info("Calling Gemini for FIR generation...")
            response = self.model.generate_content(prompt)
            text = response.text.strip()

            # Strip markdown fences
            text = re.sub(r"```(?:json)?", "", text).strip()
            text = text.rstrip("`").strip()

            fir_data = json.loads(text)

            # Build FIRDraft from Gemini output
            # Safely extract each field — don't crash on missing keys
            fir = FIRDraft(
                incident_date=fir_data.get("incident_date"),
                incident_time=fir_data.get("incident_time"),
                location=fir_data.get("location"),
                coordinates=fir_data.get("coordinates") or coord_str,
                accident_type=fir_data.get("accident_type"),
                description=fir_data.get("description"),
                vehicles_involved=fir_data.get("vehicles_involved", [])
                    or additional_info.vehicle_numbers,
                injuries=fir_data.get("injuries"),
                injuries_count=fir_data.get("injuries_count")
                    or additional_info.injuries_count or None,
                witnesses=fir_data.get("witnesses"),
                reporting_person=fir_data.get("reporting_person"),
                contact=fir_data.get("contact"),
                nearest_police_station=fir_data.get("nearest_police_station")
                    or nearest_police,
                notes=fir_data.get("notes")
            )

            self.logger.info(
                f"FIR generated successfully "
                f"(location: {fir.location})"
            )
            return fir

        except Exception as e:
            self.logger.warning(
                f"Gemini FIR generation failed ({e}), using fallback"
            )
            return self._build_fallback_fir(
                additional_info, lat, lng,
                nearest_police, lang
            )

    def _build_fallback_fir(
        self,
        additional_info,
        lat, lng,
        nearest_police,
        lang
    ) -> FIRDraft:
        """
        Build a minimal FIR when Gemini is unavailable.
        Uses only the structured additional_info fields.
        Better than returning an error — user can still share something.
        """
        coord_str = None
        if lat and lng:
            coord_str = f"{lat:.4f}°N, {lng:.4f}°E"

        type_labels = ACCIDENT_TYPE_LABELS.get(lang, ACCIDENT_TYPE_LABELS["en"])
        accident_type_display = None
        if additional_info.accident_type:
            accident_type_display = type_labels.get(
                additional_info.accident_type,
                additional_info.accident_type
            )

        if lang == "hi":
            description = (
                "सड़क दुर्घटना हुई। विस्तृत विवरण के लिए "
                "RoadSoS ऐप की चैट हिस्ट्री देखें।"
            )
            injuries_text = (
                f"{additional_info.injuries_count} व्यक्ति घायल"
                if additional_info.injuries_count else None
            )
            witness_text = (
                f"लगभग {additional_info.witnesses} गवाह"
                if additional_info.witnesses else None
            )
        else:
            description = (
                "A road traffic accident occurred at the reported location. "
                "Please refer to the RoadSoS chat history for full details."
            )
            injuries_text = (
                f"{additional_info.injuries_count} person(s) injured"
                if additional_info.injuries_count else None
            )
            witness_text = (
                f"Approximately {additional_info.witnesses} witness(es) present"
                if additional_info.witnesses else None
            )

        return FIRDraft(
            incident_date=datetime.utcnow().strftime("%Y-%m-%d"),
            incident_time=None,
            location=None,
            coordinates=coord_str,
            accident_type=accident_type_display,
            description=description,
            vehicles_involved=additional_info.vehicle_numbers or [],
            injuries=injuries_text,
            injuries_count=additional_info.injuries_count or None,
            witnesses=witness_text,
            reporting_person=additional_info.reporting_person_name or "Anonymous",
            contact=additional_info.reporting_person_phone or
                    "Available via RoadSoS emergency response",
            nearest_police_station=nearest_police,
            notes=None
        )


# ── Singleton ────────────────────────────────────────────────

_report_service: Optional[ReportService] = None

def get_report_service() -> ReportService:
    global _report_service
    if _report_service is None:
        _report_service = ReportService()
    return _report_service
