from sqlalchemy import Column, String, Float, Integer, JSON, DateTime, Boolean
from sqlalchemy import Text
from database import Base
from datetime import datetime
import uuid


class TriageSession(Base):
    __tablename__ = "triage_sessions"

    id: str = Column(
        String(36), primary_key=True,
        default=lambda: str(uuid.uuid4())
    )
    session_id: str = Column(
        String(36), nullable=False, index=True
        # FK to chat_sessions.id (soft reference, no hard FK constraint
        # to keep it simple and avoid cascade complexity)
    )
    created_at: datetime = Column(DateTime, default=datetime.utcnow)
    updated_at: datetime = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Location at time of triage start
    lat: float = Column(Float, nullable=False)
    lng: float = Column(Float, nullable=False)
    state_code: str = Column(String(5), nullable=True)  # "HR" | "DL"

    # Language for all questions and responses
    lang: str = Column(String(5), default="en")

    # Initial injury description from user
    initial_description: str = Column(Text, nullable=False)

    # Triage state machine
    status: str = Column(String(20), default="in_progress")
    # values: "in_progress" | "completed" | "abandoned"

    # Questions list (generated by Gemini at start, stored as JSON array)
    # Format: [{"question": "...", "weight": 2.0}, ...]
    questions: list = Column(JSON, default=list)

    # User answers so far (parallel array to questions)
    # Format: [{"answer": "...", "score_contribution": 1.5}, ...]
    answers: list = Column(JSON, default=list)

    # Current question index (0-based)
    current_question_index: int = Column(Integer, default=0)

    # Running severity score (updated after each answer)
    severity_score: float = Column(Float, default=0.0)

    # Final results (populated when status = "completed")
    severity_level: str = Column(String(20), nullable=True)
    # "low" | "medium" | "high" | "critical"
    recommendation: str = Column(Text, nullable=True)
    emergency_services: dict = Column(JSON, nullable=True)
    nearest_trauma_centre: dict = Column(JSON, nullable=True)
    auto_stopped: bool = Column(Boolean, default=False)
    # True if stopped early due to critical severity
